INSERT INTO USER (FIRSTNAME, SURNAME, POSITION, GITHUB_URL) VALUES('dev1a', 'dev1b', 'JUNIOR_DEV','https://github.com/dev1b');
INSERT INTO USER (FIRSTNAME, SURNAME, POSITION, GITHUB_URL) VALUES('dev2a','dev2b','INTERMEDIATE_DEV','https://github.com/dev2b');
INSERT INTO USER (FIRSTNAME, SURNAME, POSITION, GITHUB_URL) VALUES('dev3a','dev3b','TEAM_LEAD','https://github.com/dev3b');
INSERT INTO USER (FIRSTNAME, SURNAME, POSITION, GITHUB_URL) VALUES('dev4a','dev4b','SENIOR_DEV','https://github.com/dev4b');
INSERT INTO USER (FIRSTNAME, SURNAME, POSITION, GITHUB_URL) VALUES('dev5a','dev5b','SENIOR_DEV','https://github.com/dev5b');
